[openai]
OPENAI_API_KEY = "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"
[google]
GOOGLE_API_KEY = "AIzaSyCW3XY38cv1cV3eTGNk4tRMLyHQK25fUt0"
